services:
  notebooks:
    build:
      context: ./
      dockerfile: Dockerfile
      target: getml-demo
      args:
        - GETML_VERSION=$GETML_VERSION
    networks:
      - notebooks_network
    ports:
      - "1709:1709"
      - "8888:8888"

networks:
  notebooks_network: