#!/bin/bash

export GETML_DOWNLOAD_PATH='https://static.getml.com/private/0.12/'
export GETML_ENGINE='getml-0.12.0-rc.1.linux-beta.tar.xz'
export GETML_API='getml-0.12.0_datasets.3-py3-none-any.whl'

# Install getML
######
# engine
curl $GETML_DOWNLOAD_PATH$GETML_ENGINE --output getml_engine.tar.xz
cd $HOME
mkdir -p $HOME/binder/getml
tar -xJf getml_engine.tar.xz -C $HOME/binder/getml/ --strip-components=1
rm getml_engine.tar.xz

# python-api
curl $GETML_DOWNLOAD_PATH$GETML_API -OJ
pip install $HOME/$GETML_API
rm $HOME/$GETML_API


# Jupyter serverextension
######
# getML labextension
mv $HOME/binder/getml-serverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/
jupyter serverextension enable --sys-prefix getml-serverextension

# official & contribs
jupyter serverextension enable --py jupyter_server_proxy --sys-prefix
# jupyter serverextension enable --py jupyterlab_git --sys-prefix
# jupyter serverextension enable --py jupyterlab_iframe --sys-prefix
# jupyter serverextension enable --py nbdime --sys-prefix
# jupyter serverextension enable --py jupyter_offlinenotebook --sys-prefix


# Install & enable jupyter nbextensions
######
# https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html
# jupyter contrib nbextension install --sys-prefix


# jupyter nbextension enable jupyter_server_proxy/tree --sys-prefix
# jupyter nbextension enable toc2/main --sys-prefix
# jupyter nbextensions_configurator enable --sys-prefix


# Install JupyterLab extensions
######
jupyter labextension install @jupyterlab/server-proxy
# jupyter labextension install @jupyterlab/toc
# jupyter labextension install @jupyterlab/shortcutui
# jupyter labextension install jupyter-offlinenotebook
# jupyter labextension install jupyterlab_iframe


# Load jupyter presets
######
# includes user-settings for jupyterlab extensions & jupyter_notebook_config
mv $HOME/binder/.jupyter $HOME/

# other extensions
nbdime extensions --enable --sys-prefix


# getML demo setup
######
# mkdir -p $HOME/.getML/getml-0.12-beta-linux
mv $HOME/binder/.getML $HOME/


# Setup a workspace
######
jupyter lab workspaces import $HOME/binder/workspace.json
# jupyter lab workspaces import $HOME/binder/workspace-dev.json